Minor error handling improvements.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,21 +44,22 @@ jobs:
         run: ./core ${{ matrix.version }}
       - name: Ensure 'core' script fails
         run: |
+          set -x
           exit_code=0
           ./core foo || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           ./core graalvm- || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           ./core graalvm-ce || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           ./core graalvm-ce-java8-22.1.0 || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           ./core graalvm-ce-java11 || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           ./core graalvm-ce-java11-0.0.0 || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           ./core graalvm-ee-java11-0.0.0 || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
           export GRAAL_EE_DOWNLOAD_TOKEN="invalid"
-          ./core graalvm-ee-java17-22.1.0 || exit_code=$?
-          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; exit 1; }
+          ./core graalvm-ee-java11-22.1.0 || exit_code=$?
+          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
